### ISSUE TITLE
Compatibility with Apache Commons Daemon / JSVC

### ISSUE THREAD

**Issue by qprotex** [jnasmartcardio/jnasmartcardio#33]
The following code works perfectly when calling the JAR directly in console

```
public static void main(String[] args) throws CardException, GPException, NoSuchAlgorithmException {
		GlobalPlatform gp;
		Card card;
		CardTerminal terminal = TerminalManager.getTheReader(null);
		card = terminal.connect("*");
		card.beginExclusive();
		gp = new GlobalPlatform(card.getBasicChannel());
		gp.select(null);
		byte[] info = gp.getCPLC();
		String cardInfo = HexUtils.encodeHexString_imp(info);
		card.disconnect(true);
		System.out.println("Hexa Card Info: " + cardInfo);
	}

```

When using JSVC (From Apache Commons Daemon library) to launch the JAR as a daemon, I get a JnaPCSCException (SCardEstablishContext got response 0x8010001d (SCARD_E_NO_SERVICE: The Smart card resource manager is not running.)

> Java VM created successfully
> Class org/apache/commons/daemon/support/DaemonLoader found
> Native methods registered
> java_init done
> Daemon loading...
> Daemon loaded successfully
> java_load done
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:241)
> Caused by: jnasmartcardio.Smartcardio$EstablishContextException: jnasmartcardio.Smartcardio$JnaPCSCException: SCardEstablishContext got response 0x8010001d (SCARD_E_NO_SERVICE: The Smart card resource manager is not running.)
> 	at jnasmartcardio.Smartcardio$JnaTerminalFactorySpi.engineTerminals(Smartcardio.java:81)
> 	at javax.smartcardio.TerminalFactory.terminals(TerminalFactory.java:351)
> 	at apdu4j.TerminalManager.getTheReader(TerminalManager.java:228)
> 	at com.st.simple.card.client.Client.main(Client.java:29)
> 	at com.st.simple.card.client.Client.start(Client.java:58)
> 	... 5 more
> Caused by: jnasmartcardio.Smartcardio$JnaPCSCException: SCardEstablishContext got response 0x8010001d (SCARD_E_NO_SERVICE: The Smart card resource manager is not running.)
> 	at jnasmartcardio.Smartcardio.check(Smartcardio.java:960)
> 	at jnasmartcardio.Smartcardio.check(Smartcardio.java:951)
> 	at jnasmartcardio.Smartcardio.access$000(Smartcardio.java:34)
> 	at jnasmartcardio.Smartcardio$JnaTerminalFactorySpi.engineTerminals(Smartcardio.java:79)
> 	... 9 more
> Cannot start daemon
> java_start failed
> remove_pid_file: open /tmp/file.pid: fd=3
> Service exit with a return value of 5
> 

The fact that the JAR works directly makes me believe the code is right but something related to permissions is maybe causing the issue. Any ideas?

**Comment by yonran** [comment]
Sorry I forgot to respond to this. `SCARD_E_NO_SERVICE` means that the daemon is not running. On Windows and Mac, this usually means that you don’t have a smart card reader plugged in anywhere, since the system daemon only runs whenever there is at least one smart card reader. On Linux you might need to install the `pcscd` daemon first.
